---
title: "notes"
author: "Yang Liu"
date: 07-14-2023
format: 
   revealjs:
    slide-number: c/t
    width: 1600
    height: 900
    theme: simple
    incremental: true
    scrollable: true
execute:
  echo: false
  warning: false
editor: visual
---

## Background

I hope to use Demographic and Health Surveys (DHS) data to perform a descriptive study or studies that explores the relationship between female genital cutting (FGC) and reproductive health indices (sexual activity, contraception, fertility, and infertility). I could also look at the relationship between factors as they relate to women empowerment, mass media exposure, and FGC or perception of FGC in women. I'm hoping our discussion could help me decide on which topic to start with first and review my plan for study design/analysis.

Just to review, DHS has publicly assessable, deidentified data of over 400 surveys in more than 90 countries. [https://dhsprogram.com/data/dataset_admin/index.cfm?CFID=128425097&CFTOKEN=50ffe6b7de9bebad-53EF3AA3-DA30-33FA-9A92F5605E5050DC]


## Data source

DHS Demographic and Health survey data in Sierra Leone since 2019

codebook: https://www.dhsprogram.com/publications/publication-dhsg4-dhs-questionnaires-and-manuals.cfm

**IR: Individual (Women's) Recode** Unit of analysis: De facto woman interviewed Contains all the data collected in the Woman's Questionnaire for de facto women plus some variables from the Household Questionnaire. Up to 20 births in the birth history (see also BR file), and up to 6 children under age 5 (see also KR file), for whom pregnancy and postnatal care as well as immunization, health and nutrition data were collected, can be found as repeated variables in this file. This dataset is used for most woman-level analysis including marriage and sexual activity (Chapter 4), fertility and fertility preferences (Chapters 5 and 6), family planning (Chapter 7), anthropometry and anemia in women (Chapter 11), malaria prevention for women (Chapter 12), HIV/AIDS (Chapters 13 and 14), women's empowerment (Chapter 15), adult and maternal mortality (Chapter 16), and domestic violence (Chapter 17).

https://www.dhsprogram.com/pubs/pdf/DHSG1/Guide_to_DHS_Statistics_DHS-7_v2.pdf page 36

## Research question 1

  The relationship between female genital cutting (FGC) and reproductive health indices (sexual activity, contraception, fertility, and infertility).

    Prevalence of female genital cutting in 2019 report: 83% of women age 15-49 are circumcised.2013 report: 97.3%
    
    Describe demographic of circumcised women and uncircumcised women in SL;
describe these women's reproductive health indices

## Research question 2
  The relationship between factors as they relate to women empowerment, mass media exposure, and FGC or perception of FGC in women.

    Describe women empowerment in circumcised women and uncircumcised women. 
    women’s empowerment:
    (a) labour force participation (measured by current employment status); 
    (b) acceptance of wife beating under some circumstances (e.g. neglects children, burns food, refuses to have sex with husband, argues with husband and visitations without permission from husband); 
    (c) knowledge level (e.g. education level, listens, to the radio, reads newspaper and watches television); 
    (d) decision-making power (decision on respondent’s healthcare, house earning, household purchases and visiting family members).

## Research question 3    
 fgc prevalence in SL: 2013 97.3% vs 2019 83%; 
 hypothesis: women empowerment and mass media exposure contributed to the decline of fgc prevalence.
 women were circumcised at very young ages. fgc decision making: young girls or their parents? 
 study population: 2013 and 2019 survey age 15-49 
 compare women empowerment, internet use, 

## Study design

Survey, retrospective, cross-sectional, descriptive

## Study population

```{r}
#| echo: false
library(DiagrammeR)
grViz("digraph flowchart {
      # node definitions with substituted label text
      node [fontname = Helvetica, shape = rectangle]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']

      # edge definitions with the node IDs
      tab1 -> tab2 -> tab3 -> tab4; tab3 -> tab5;
      }

      [1]: 'Women in 2019 SL DHS N=15574'
      [2]: 'Missing fgc data n=930'
      [3]: 'Study population N=14,692'
      [4]: 'Circumcised women n=12,932'
      [5]: 'Uncircumcised women n=1,760'
      ")
```

## Objective

describe demographic of circumcised women and uncircumcised women in SL;
describe these women's reproductive health indices

## FGC Survey Questionnaire

/G100 "Ever heard of female circumcision"

/G101 "Ever heard of genital cutting (probed)"

/G102 "Respondent circumcised"

/G103 "Flesh removed from genital area"

/G104 "Genital area just nicked without removing any flesh"

/G105 "Genital area sewn closed"

/G106 "Age at circumcision (in years)"

/G107 "Person who performed circumcision"

/G108 "Number of daughters circumcised"

/G109 "NA - Line number of daughter most recently circumcised (from Birth History)"

/G110 "NA - Flesh removed from genital area of daughter"

/G111 "NA - Genital area of daughter just nicked without removing flesh"

/G112 "NA - Genital area of daughter sewn closed"

/G113 "NA - Age of daughter at circumcision (in years)"

/G114 "NA - Person who performed circumcision of daughter"

/G115 "NA - Any daughter not circumcised"

/G116 "NA - Intends to have daughter(s) circumcised in future"

/G117A "NA - Cleanliness/hygiene: Female circumcision benefit"

/G117B "NA - Social acceptance: Female circumcision benefit"

/G117C "NA - Better marriage prospects: Female circumcision benefit"

/G117D "NA - Virginity/prevent premarital sex: Female circumcision benefit"

/G117E "NA - Greater sexual pleasure for men: Female circumcision benefit"

/G117F "NA - Religious approval: Female circumcision benefit"

/G117G "NA - CS: Female circumcision benefit"

/G117H "NA - CS: Female circumcision benefit"

/G117I "NA - CS: Female circumcision benefit"

/G117J "NA - CS: Female circumcision benefit"

/G117X "NA - Other: Female circumcision benefit"

/G117Y "NA - No benefit from female circumcision"

/G118 "Female circumcision required by religion"

/G119 "Female circumcision: continue or be stopped"

/GIDX\$01-20 "Daughter's index to birth history"

/G121\$01-20 "Is daughter circumcised"

/G122\$01-20 "Daughter's age at circumcision"

/G123\$01-20 "Was daughter genital area sewn closed"

/G124\$01-20 "Who performed daughter's circumcision"

## Exposure

female genital cutting (FGC)

## Primary outcome

Reproductive health indices (sexual activity, contraception, fertility, and infertility)

## Secondary outcome

## Variables of interest

-g102 fgc yes or no

-Demographic characteristics:    

## weighting variables

individual sample weight (v005)

cluster number (v001)
strata (v022 or v023)
primary sampling unit (v021)

## References

1.  Women's empowerment and female genital mutilation intention for daughters in Sierra Leone- a multilevel analysis

outcome variable: intention for cutting daughters

individual-level factors: women’s empowerment, including (a) labour force
participation (measured by current employment status); (b) acceptance of wife beating under some circumstances (e.g. neglects children, burns food, refuses to have
sex with husband, argues with husband and visitations without permission from husband); (c) knowledge level (e.g. education level, listens, to the radio, reads newspaper
and watches television); and (d) decision-making power (decision on respondent’s healthcare, house earning, household purchases and visiting family members).other factors: age, household wealth index (poorest, poorer, middle, richer, richest), partner’s education (no education, primary and secondary or higher), and fgc status.

Contextual factors:whether FGM/C is required by religion (yes or no), if it is socially accepted (yes or no), family headship (male or female) and place of residence (urban or rural).

model1: empty, no explanatory variables
model2: individual-level factors only
model3: contextual factors only
model4: full
tables: proportions, crude OR, adjusted OR
2.  Dalal K, Kalmatayeva Z, Mandal S et al. Adolescent girls' attitudes toward female genital mutilation: a study in seven African countries \[version 1; referees: 2 approved, 1 not approved\] F1000Research 2018, 7:343 (doi:10.12688/f1000research.14142.1)

didn't use sample weight- regional population size within a nation has no influence on this study (weight is normalized at national level).

3.  Anemia and Associated Factors Among Lactating Women in Sierra Leone: An Analysis of the Sierra LeoneDemographic and Health Survey 2019

   DOI: 10.1177/11786388221105732

    Methods: The following variables were incorporated in the analysis: individual sample weight, sample strata for sampling errors and cluster number. Analysis was carried out based on the weighted count to account for the unequal probability sampling in different strata and to ensure representativeness of the survey results at the national and regional level.

4.  DHS program

    The DHS Program recode files are exported into several dataset types. Below is a description of the dataset types referred to in the Guide to DHS Statistics, together with the unit of analysis (or case) for each dataset: **HR: Household Recode** Unit of analysis: Households Includes household characteristics, the household roster, and biomarkers rosters as repeating sets of variables. This dataset is used for calculation of household level indicators such as water and sanitation (see Chapter2). **PR: Household members (or Persons) Recode** Unit of analysis: Household member Includes characteristics of household members including age, sex, marital status, education, as well as biomarker measurement information. The dataset includes both de facto and de jure household members. It also includes the characteristics of the households where the individual lives or was visiting. This dataset is used for analysis of education of household members (Chapter 2) and of anthropometry and anemia in children under age 5 (Chapter 11). **IR: Individual (Women's) Recode** Unit of analysis: De facto woman interviewed Contains all the data collected in the Woman's Questionnaire for de facto women plus some variables from the Household Questionnaire. Up to 20 births in the birth history (see also BR file), and up to 6 children under age 5 (see also KR file), for whom pregnancy and postnatal care as well as immunization, health and nutrition data were collected, can be found as repeated variables in this file. This dataset is used for most woman-level analysis including marriage and sexual activity (Chapter 4), fertility and fertility preferences (Chapters 5 and 6), family planning (Chapter 7), anthropometry and anemia in women (Chapter 11), malaria prevention for women (Chapter 12), HIV/AIDS (Chapters 13 and 14), women's empowerment (Chapter 15), adult and maternal mortality (Chapter 16), and domestic violence (Chapter 17). **BR: Births Recode** Unit of analysis: Birth Contains the full birth history of all women interviewed, including information on pregnancy and postnatal care as well as immunization, health and nutrition data for children born in the last 5 years. Data for the mother of each of these children are also included. This dataset is used for fertility (Chapter 5) and mortality (Chapter 8) analysis. **KR: Kids Recode** Unit of analysis: Child under age 5 born to a woman interviewed Contains the information related to the child's pregnancy and postnatal care and immunization, health and nutrition data. The data for the mother of each of these children is also included. This dataset is used to look at child health indicators such as immunization coverage, vitamin A supplementation, recent occurrences of diarrhea, fever, and cough for young children and treatment of childhood diseases (Chapter 10), nutrition of young children (Chapter 11), and malaria prevention and treatment (Chapter 12). **MR: Men's Recode** Unit of analysis: De facto man interviewed Contains all data collected in the Man's Questionnaire de facto men plus some variables from the Household Questionnaire. This dataset is used for most man-level analysis including marriage and sexual activity (Chapter 4), fertility preferences (Chapters 6), and HIV/AIDS (Chapters 13 and 14). **CR: Couples Recode** Unit of analysis: Married woman and man Contains data for married or living together women and men who both declared that they are married (living together) to each other and with completed individual interviews. This dataset is the result of linking the IR and MR files, based on whom they both declared as partners. In polygynous societies a man's data may be linked to more than one woman's data. This dataset is used for analysis of couples, principally related to HIV (Chapters 13 and 14). **FW: Fieldworker's Dataset** Unit of analysis: Fieldworker Contains the basic characteristics of each fieldworker who participated in the survey, including their age, sex, marital status, level of education, region of residence, languages, and prior experience with DHS or other surveys. Data from the fieldworker's dataset may be linked to the survey responses using the interviewer, supervisor, field editor, or biomarker specialists IDs.

    sampling and weighting: https://www.youtube.com/watch?v=YpXPWMUsb94

5.  Association between exposure to family planning messages on different mass media channels and the utilization of modern contraceptives among young women in Sierra Leone: insights from the 2019 Sierra Leone Demographic Health Survey

    https://doi.org/10.1186/s12905-022-01974-w

6.  Prevalence and factors associated with underweight among 15--49-year-old women in Sierra Leone: a secondary data analysis of Sierra Leone demographic health survey of 2019 https://doi.org/10.1186/s12905-023-02358-4

7.  Prevalence of risk factors for human immunodeficiency virus among women of reproductive age in Sierra Leone: a 2019 nationwide survey

    https://doi.org/10.1186/s12879-022-07037-7

note:  render Quarto documents into self contained HTML
format:
  html:
    embed-resources: true
